### ISSUE TITLE
Eu gosto de CraftedWeb, se você está atualmente usando php7 ou php5.6 para recompra

### ISSUE THREAD

**Issue by yuanf225** [erictemponi/CraftedWeb#1]
Eu gosto de CraftedWeb, se você está atualmente usando php7 ou php5.6 para recompra

**Comment by erictemponi** [comment]
> Eu gosto de CraftedWeb, se você está atualmente usando php7 ou php5.6 para recompra

Use o PHP 5.6. O site não está adequado para rodar nas versões mais recentes do PHP.

**Comment by yuanf225** [comment]
How to make it support Azeroth core

**Comment by erictemponi** [comment]
Just change the SQL queries inside the site so it can be used with AzerothCore database structure
