### ISSUE TITLE
I am going to use this system, can it support ac?

### ISSUE THREAD

**Issue by yuanf225** [erictemponi/CraftedWeb#2]
I am going to use this system, can it support ac?

**Comment by erictemponi** [comment]
It doesn't support SRP6, so it won't work with new AC servers.

**Comment by yuanf225** [comment]
Do you plan to update the source code to support SRP6

**Comment by erictemponi** [comment]
Yes, maybe on the weekend.

**Comment by yuanf225** [comment]
Great, thank you

**Comment by yuanf225** [comment]
hey man, I am looking forward to your update

**Comment by yuanf225** [comment]
hi bro is there any new progress?

**Comment by yuanf225** [comment]
hi

**Comment by erictemponi** [comment]
Hi, my friend, sorry for late answering. I'm changing the code so it can work with SRP6. Account creation and login are working, but I need to fix e-mail and password change functions yet. I'll create a new branch with SRP6 support and fix the bugs later on commits
